### ISSUE TITLE
Missing levels?

### ISSUE THREAD

**Issue by okazamax** [MiniBobbo/GameOff2019#2]
Hi MiniBobbo,

For a university project, we have chosen to do testing on this here project and are having a few issues that we'd love your help with if you can spare some time. 

1) We noticed that the assets folder only has levels up to 14.
2) We're wondering how exactly to compile all of the code, we were able to load the lobby screen but not much else.

Any help you can give would be incredible. You can reach me through this or (preferably) through email: okazamax AT oregonstate dot edu

**Comment by okazamax** [comment]
@MiniBobbo

**Comment by MiniBobbo** [comment]
Hi @okazamax!  I sent you an email about this also, but I uploaded the missing assets.  I set the assets folder into my gitignore in the middle of the jam for some reason.  I don't remember why now but it made sense to me at the time.  Everything should be up there now.
